---
- name: Pastikan service native Calculator dimatikan (jika ada)
  systemd:
    name: calculator
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Buat direktori aplikasi calculator
  file:
    path: /opt/calculator
    state: directory
    mode: '0755'

- name: Copy script aplikasi calculator
  template:
    src: calculator.py.j2
    dest: /opt/calculator/calculator.py
    mode: '0755'

- name: Copy Dockerfile
  template:
    src: Dockerfile.j2
    dest: /opt/calculator/Dockerfile
    mode: '0644'

- name: Build Docker Image untuk Calculator
  docker_image:
    name: calculator-api
    build:
      path: /opt/calculator
    source: build
    force_source: yes

- name: Buat Docker Network app-net
  docker_network:
    name: app-net
    state: present

- name: Jalankan Container Calculator
  docker_container:
    name: calculator-api
    image: calculator-api:latest
    ports:
      - "5000:5000"
    networks:
      - name: app-net
    state: started
    recreate: yes
    restart: yes
    restart_policy: always

