FROM python:3.9-slim

WORKDIR /opt/calculator

# Install dependencies
RUN pip install flask hazelcast-python-client

# Copy application script
COPY calculator.py .

# Expose port
EXPOSE 5000

# Run application
CMD ["python", "calculator.py"]
