# Inventory file untuk 3 Host Kali Linux (Pure Configuration Management)

[control_node]
localhost ansible_connection=local

[webservers]
kali-web-1 ansible_host=192.168.56.11
kali-web-2 ansible_host=192.168.56.12

[dbservers]
kali-db-1 ansible_host=192.168.56.13

[managed_nodes:children]
webservers
dbservers

[managed_nodes:vars]
# Sesuaikan username dan password di bawah ini dengan akun di VM Kali Linux Anda
ansible_user=kali
ansible_password=kali
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
