[control_node]
localhost ansible_connection=local

[webservers]
ubuntu_1 ansible_host=13.214.185.65

[k3s_nodes]
ubuntu_2 ansible_host=18.141.212.90

[cacheservers]
ubuntu_3 ansible_host=3.0.201.164

[managed_nodes:children]
webservers
k3s_nodes
cacheservers

[managed_nodes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/orchest_key
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
