[control_node]
localhost ansible_connection=local

[webservers]
ubuntu-1 ansible_host=192.168.56.11

[k8s_nodes]
ubuntu-2 ansible_host=192.168.56.12

[cacheservers]
ubuntu-3 ansible_host=192.168.56.13

[managed_nodes:children]
webservers
k8s_nodes
cacheservers

[managed_nodes:vars]
ansible_user=vboxuser
ansible_password={{ vault_ansible_password }}
ansible_become_password={{ vault_ansible_become_password }}
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'




