---
- name: Cek apakah k3s sudah terinstal
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install k3s (Lightweight Kubernetes)
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true INSTALL_K3S_EXEC="--disable traefik" INSTALL_K3S_VERSION="v1.28.9+k3s1" sh -s - --write-kubeconfig-mode 644
  when: not k3s_binary.stat.exists

- name: Pastikan service k3s berjalan
  systemd:
    name: k3s
    masked: no
    state: started
    enabled: yes

- name: Tunggu k3s node menjadi Ready
  command: k3s kubectl get nodes
  register: nodes_result
  until: "' Ready ' in nodes_result.stdout"
  retries: 15
  delay: 10
  changed_when: false

- name: Install pip untuk Python3
  apt:
    name: python3-pip
    state: present

- name: Cek jika kubernetes module terpasang untuk Python
  pip:
    name:
      - kubernetes
      - pyyaml
    state: present

- name: Buat Deployment Hello World (Nginx)
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-world
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: hello-world
        template:
          metadata:
            labels:
              app: hello-world
          spec:
            containers:
            - name: nginx
              image: nginx:alpine
              ports:
              - containerPort: 80

- name: Ekspos Hello World melalui NodePort
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: hello-world-service
        namespace: default
      spec:
        type: NodePort
        ports:
          - port: 80
            targetPort: 80
            nodePort: 30080
        selector:
          app: hello-world
