---
app_name: "Ansible Enterprise Lab"
environment_name: "Development"
admin_email: "admin@devops.local"
timezone: "Asia/Jakarta"

hazelcast_host: "{{ hostvars['ubuntu_3']['ansible_host'] }}"
hazelcast_port: 5701

postgres_db: "mydb"
