---
- name: Pastikan service native Hazelcast dimatikan (jika ada)
  systemd:
    name: "{{ hazelcast_service_name | default('hazelcast') }}"
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Buat direktori konfigurasi Hazelcast
  file:
    path: "{{ hazelcast_install_dir | default('/opt/hazelcast') }}/config"
    state: directory
    mode: '0755'

- name: Salin konfigurasi Hazelcast kustom
  template:
    src: hazelcast.xml.j2
    dest: "{{ hazelcast_install_dir | default('/opt/hazelcast') }}/config/hazelcast.xml"

- name: Jalankan Container Hazelcast
  docker_container:
    name: hazelcast-cache
    image: hazelcast/hazelcast:5.3
    ports:
      - "5701:5701"
    volumes:
      - "{{ hazelcast_install_dir | default('/opt/hazelcast') }}/config/hazelcast.xml:/opt/hazelcast/config/hazelcast.xml:ro"
    state: started
    restart: yes
    restart_policy: always

